name: Deploy to Azure
on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Add permissions at workflow level
permissions:
  actions: read
  contents: write
  checks: read
  pull-requests: read
  statuses: read

jobs:
  verify-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Wait for other checks
        run: |
          echo "Waiting for workflows to complete..."
          sleep 30 # Wait for other workflows to start/complete
          
      - name: Check workflow status
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "Checking workflow statuses..."
          
          # Check lint workflow status
          gh run list --workflow=lint.yml --branch ${{ github.ref_name }} --json conclusion --jq '.[0].conclusion' 
          | grep -q "success" || exit 1

          # Check test workflow status
          gh run list --workflow=test.yml --branch ${{ github.ref_name }} --json conclusion --jq '.[0].conclusion' 
          | grep -q "success" || exit 1

          # Check security scan workflow status
          gh run list --workflow=security-scan.yml --branch ${{ github.ref_name }} --json conclusion --jq '.[0].conclusion' 
          | grep -q "success" || exit 1

  deploy:
    needs: [verify-checks]
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: |
          cd src
          npm install

      - name: Login to Azure using Service Principal
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Zip the application
        run: |
          cd src
          zip -r ../webapp.zip ./*

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: cnsdevproj
          package: webapp.zip

